### ISSUE TITLE
I'm having trouble making this work

### ISSUE THREAD

**Issue by KTsarlz** [nellywg/cas-dark-mode#1]
I pasted the code in the right path, under version 3.2.0, however slack still looks like the default one. I tried to reload the app and restart. But still no luck. 

Any tips on how to apply? I tried the other dark modes found on github and all exhibits this same behavior

**Comment by ghost** [comment]
@KTsarlz , which file did you pasted your code in? You want to make sure that it's 'ssb-interop.js' and at the end of the file after closing tag. 

And also this will only work for windows desktop app. I haven't done the testing on ios yet. 

Edit;
On another note, you can also try the code from the other creator, 
https://github.com/widget-/slack-black-theme
And also this trick form La Cour: http://blog.lacour.me/making-slack-night-mode
I've tried both, and they works perfectly fine.

**Comment by KTsarlz** [comment]
I'm trying to edit the ssb-interop.js file as mentioned on this repo and other repos. What's confusing is, it did worked 1 time and when I tried to change the CSS using yours, and others nothing works anymore. I am using 3.2.0 and the file in it. Lacour's version also didn't work

**Comment by ghost** [comment]
I tried to replicate your issue,  experienced the same thing at first, but got it works at last. Here's what I did:

1. Clean uninstall slack app from Windows, make sure to delete the whole slack folder from %localappdata% to remove all the saved preferences that might have.
2. Re-install the slack app. I installed v 3.2.0
3. Paste in the code on 'ssb-interop.js' file. Try to refresh and restart. At this point, nothing works, and it still showing the default theme. So I removed the piece of code, and
4. Change the sidebar to my custom theme color. **File > Preferences > Sidebar**, and click to customize the color. Here are the colors that I used for my theme.
`#202234,#0073c0,#00aeff,#ffffff,#525666,#a3a8b2,#39b771,#fa2a92`
5. Put in back the code on 'ssb-interop.js', and try to reload or restart the app.

You might be able to skip step #3. Somehow by doing the step #4 fix the problem. Not 100% sure why. But hopefully this trick works for you as well. Best luck.

**Comment by KTsarlz** [comment]
Wow. I just did that. Not sure why and if this is caching or what. But thanks alot!!!
